language: Swift
osx_image: xcode9.3
xcode_project: Scripty.xcodeproj
xcode_scheme: Scripty

before_install:
  - pod repo update
  - pod install

before_script:
- openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/certs/dev.cer.enc -d -a -out scripts/certs/dev.cer
- openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/certs/dev.p12.enc -d -a -out scripts/certs/dev.p12
- chmod a+x scripts/add_key.sh
- ./scripts/add_key.sh

script:
  - set -o pipefail
  - xcodebuild test -workspace Scripty.xcworkspace -scheme Scripty -sdk macosx10.13 ONLY_ACTIVE_ARCH=NO -enableCodeCoverage YES -destination 'platform=OS X,arch=x86_64' | xcpretty -c 
  
after_success:
  - bash <(curl -s https://codecov.io/bash)