language: Swift
osx_image: xcode9.3
xcode_project: Scripty.xcodeproj
xcode_scheme: Scripty

before_install:
  - pod repo update
  - pod install

script:
  - set -o pipefail
  - xcodebuild test -workspace Scripty.xcworkspace -scheme Scripty -sdk macosx10.13 ONLY_ACTIVE_ARCH=NO -enableCodeCoverage YES -destination 'platform=OS X,arch=x86_64' | xcpretty -c 
  
after_success:
  - bash <(curl -s https://codecov.io/bash)